// import Footer from '../../components/Footer'
// import Header from '../../components/Header'
import Footer from '../../components/Footer'
import Header from '../../components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const containerStyle = {
    position: 'relative', 
    left:'50%', 
    transform: 'translateX(-50%)',
    maxWidth:'900px', display:'flex' ,flexDirection:'column'
  };

  return (
    <html lang="en">
      <body className={inter.className} style={containerStyle}>
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
